services:
  flask_app:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - FLASK_SITE_USER=username
      - FLASK_SITE_PASS=password
      - GOOGLE_CLIENT_ID=46312638469-rcr1m6pmtpaq9siqoe81d699a9pbkveu.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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